[clang]
# the
compile-commands-directory = ""

# the path of builtin headers that clang uses
resource-directory = "${executable}/../lib/clang/${version}"

# the commands that will be appended to the command line
append = []

# the commands that will be removed from the command line
remove = []

[completion]

[diagnostic]

[inlay-hint]
